apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260527-224618-y64hb8v379dl-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260527-224618-y64hb8v379dl.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260527-224618-y64hb8v379dl-service
            port:
              number: 80
